build(deps-dev): bump stylelint from 17.4.0 to 17.6.0 in the stylelint-packages group (#38)
Bumps the stylelint-packages group with 1 update:
[stylelint](https://github.com/stylelint/stylelint).

Updates `stylelint` from 17.4.0 to 17.6.0
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/stylelint/stylelint/releases">stylelint's
releases</a>.</em></p>
<blockquote>
<h2>17.6.0</h2>
<p>It adds support for extending units in <code>languageOptions</code>,
which then apply to rules like
<code>declaration-property-value-no-unknown</code>, and fixes 2
bugs.</p>
<ul>
<li>Added: support for extending units to <code>languageOptions</code>
(<a
href="https://redirect.github.com/stylelint/stylelint/issues/9166">#9166</a>)
(<a href="https://github.com/jeddy3"><code>@​jeddy3</code></a>).</li>
<li>Fixed: missing <code>ruleMetadata</code> when linting multiple files
with overrides (<a
href="https://redirect.github.com/stylelint/stylelint/issues/9154">#9154</a>)
(<a href="https://github.com/kovsu"><code>@​kovsu</code></a>).</li>
<li>Fixed: <code>custom-property-no-missing-var-function</code> false
positives for <code>timeline-scope</code> and
<code>animation-timeline</code> (<a
href="https://redirect.github.com/stylelint/stylelint/issues/9164">#9164</a>)
(<a
href="https://github.com/splincode"><code>@​splincode</code></a>).</li>
</ul>
<h2>17.5.0</h2>
<p>It deprecates two rule options, adds 1 rule option and fixes 7 bugs.
We've also released <a
href="https://github.com/stylelint/vscode-stylelint/releases/tag/2.1.0"><code>2.1.0</code></a>
of <a
href="https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint">our
VS Code extension</a>, which adds 8 new requested features, and our <a
href="https://www.npmjs.com/package/@stylelint/language-server">first
release</a> of the Stylelint Language Server.</p>
<ul>
<li>Deprecated: <code>*syntax</code> options from
<code>declaration-property-value-no-unknown</code> (<a
href="https://redirect.github.com/stylelint/stylelint/issues/9102">#9102</a>)
(<a
href="https://github.com/ragini-pandey"><code>@​ragini-pandey</code></a>).</li>
<li>Added: <code>ignoreMediaFeatureNameValues: {}</code> to
<code>media-feature-name-value-no-unknown</code> (<a
href="https://redirect.github.com/stylelint/stylelint/issues/8976">#8976</a>)
(<a href="https://github.com/kovsu"><code>@​kovsu</code></a>).</li>
<li>Fixed: <code>node_modules</code> not ignored when using
<code>codeFilename</code> in Node.js API (<a
href="https://redirect.github.com/stylelint/stylelint/issues/9130">#9130</a>)
(<a
href="https://github.com/adalinesimonian"><code>@​adalinesimonian</code></a>).</li>
<li>Fixed: <code>Error TS7016</code> for imported <code>css-tree</code>
types (<a
href="https://redirect.github.com/stylelint/stylelint/issues/9133">#9133</a>)
(<a
href="https://github.com/ragini-pandey"><code>@​ragini-pandey</code></a>).</li>
<li>Fixed: <code>declaration-property-value-keyword-no-deprecated</code>
false positives for function arguments (<a
href="https://redirect.github.com/stylelint/stylelint/issues/9116">#9116</a>)
(<a
href="https://github.com/ragini-pandey"><code>@​ragini-pandey</code></a>).</li>
<li>Fixed: <code>declaration-property-value-no-unknown</code> false
positives for <code>calc-size()</code> containing <code>size</code>
keyword (<a
href="https://redirect.github.com/stylelint/stylelint/issues/9105">#9105</a>)
(<a href="https://github.com/hriztam"><code>@​hriztam</code></a>).</li>
<li>Fixed: <code>no-descending-specificity</code> &amp;
<code>no-duplicate-selectors</code> false negatives for equivalent
compound selectors (<a
href="https://redirect.github.com/stylelint/stylelint/issues/8977">#8977</a>)
(<a href="https://github.com/kovsu"><code>@​kovsu</code></a>).</li>
<li>Fixed: <code>no-invalid-position-declaration</code> false positives
for <code>@mixin</code> and <code>@scope</code> (<a
href="https://redirect.github.com/stylelint/stylelint/issues/9120">#9120</a>)
(<a
href="https://github.com/ragini-pandey"><code>@​ragini-pandey</code></a>).</li>
<li>Fixed: <code>property-no-unknown</code> false negatives for
<code>types</code> (<a
href="https://redirect.github.com/stylelint/stylelint/issues/9117">#9117</a>)
(<a
href="https://github.com/Mouvedia"><code>@​Mouvedia</code></a>).</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/stylelint/stylelint/blob/main/CHANGELOG.md">stylelint's
changelog</a>.</em></p>
<blockquote>
<h2>17.6.0 - 2026-03-26</h2>
<p>It adds support for extending units in <code>languageOptions</code>,
which then apply to rules like
<code>declaration-property-value-no-unknown</code>, and fixes 2
bugs.</p>
<ul>
<li>Added: support for extending units to <code>languageOptions</code>
(<a
href="https://redirect.github.com/stylelint/stylelint/pull/9166">#9166</a>)
(<a href="https://github.com/jeddy3"><code>@​jeddy3</code></a>).</li>
<li>Fixed: missing <code>ruleMetadata</code> when linting multiple files
with overrides (<a
href="https://redirect.github.com/stylelint/stylelint/pull/9154">#9154</a>)
(<a href="https://github.com/kovsu"><code>@​kovsu</code></a>).</li>
<li>Fixed: <code>custom-property-no-missing-var-function</code> false
positives for <code>timeline-scope</code> and
<code>animation-timeline</code> (<a
href="https://redirect.github.com/stylelint/stylelint/pull/9164">#9164</a>)
(<a
href="https://github.com/splincode"><code>@​splincode</code></a>).</li>
</ul>
<h2>17.5.0 - 2026-03-19</h2>
<p>It deprecates two rule options, adds 1 rule option and fixes 7 bugs.
We've also released <a
href="https://github.com/stylelint/vscode-stylelint/releases/tag/2.1.0"><code>2.1.0</code></a>
of <a
href="https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint">our
VS Code extension</a>, which adds 8 new requested features, and our <a
href="https://www.npmjs.com/package/@stylelint/language-server">first
release</a> of the Stylelint Language Server.</p>
<ul>
<li>Deprecated: <code>*syntax</code> options from
<code>declaration-property-value-no-unknown</code> (<a
href="https://redirect.github.com/stylelint/stylelint/pull/9102">#9102</a>)
(<a
href="https://github.com/ragini-pandey"><code>@​ragini-pandey</code></a>).</li>
<li>Added: <code>ignoreMediaFeatureNameValues: {}</code> to
<code>media-feature-name-value-no-unknown</code> (<a
href="https://redirect.github.com/stylelint/stylelint/pull/8976">#8976</a>)
(<a href="https://github.com/kovsu"><code>@​kovsu</code></a>).</li>
<li>Fixed: <code>node_modules</code> not ignored when using
<code>codeFilename</code> in Node.js API (<a
href="https://redirect.github.com/stylelint/stylelint/pull/9130">#9130</a>)
(<a
href="https://github.com/adalinesimonian"><code>@​adalinesimonian</code></a>).</li>
<li>Fixed: <code>Error TS7016</code> for imported <code>css-tree</code>
types (<a
href="https://redirect.github.com/stylelint/stylelint/pull/9133">#9133</a>)
(<a
href="https://github.com/ragini-pandey"><code>@​ragini-pandey</code></a>).</li>
<li>Fixed: <code>declaration-property-value-keyword-no-deprecated</code>
false positives for function arguments (<a
href="https://redirect.github.com/stylelint/stylelint/pull/9116">#9116</a>)
(<a
href="https://github.com/ragini-pandey"><code>@​ragini-pandey</code></a>).</li>
<li>Fixed: <code>declaration-property-value-no-unknown</code> false
positives for <code>calc-size()</code> containing <code>size</code>
keyword (<a
href="https://redirect.github.com/stylelint/stylelint/pull/9105">#9105</a>)
(<a href="https://github.com/hriztam"><code>@​hriztam</code></a>).</li>
<li>Fixed: <code>no-descending-specificity</code> &amp;
<code>no-duplicate-selectors</code> false negatives for equivalent
compound selectors (<a
href="https://redirect.github.com/stylelint/stylelint/pull/8977">#8977</a>)
(<a href="https://github.com/kovsu"><code>@​kovsu</code></a>).</li>
<li>Fixed: <code>no-invalid-position-declaration</code> false positives
for <code>@mixin</code> and <code>@scope</code> (<a
href="https://redirect.github.com/stylelint/stylelint/pull/9120">#9120</a>)
(<a
href="https://github.com/ragini-pandey"><code>@​ragini-pandey</code></a>).</li>
<li>Fixed: <code>property-no-unknown</code> false negatives for
<code>types</code> (<a
href="https://redirect.github.com/stylelint/stylelint/pull/9117">#9117</a>)
(<a
href="https://github.com/Mouvedia"><code>@​Mouvedia</code></a>).</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/stylelint/stylelint/commit/f74ceafa445e0299261a8d590a27c9441dea49d1"><code>f74ceaf</code></a>
Release 17.6.0 (<a
href="https://redirect.github.com/stylelint/stylelint/issues/9180">#9180</a>)</li>
<li><a
href="https://github.com/stylelint/stylelint/commit/895f7f23e7a67e1fcc763f2e29c625bd56ce86f1"><code>895f7f2</code></a>
Add support for extending units to <code>languageOptions</code> (<a
href="https://redirect.github.com/stylelint/stylelint/issues/9166">#9166</a>)</li>
<li><a
href="https://github.com/stylelint/stylelint/commit/dd7231b971072c130fc333edf744ee01febacb6f"><code>dd7231b</code></a>
Refactor to replace <code>imurmurhash</code> with
<code>node:crypto</code> (<a
href="https://redirect.github.com/stylelint/stylelint/issues/9177">#9177</a>)</li>
<li><a
href="https://github.com/stylelint/stylelint/commit/5b6b024684b88f11a3bc84269722529e09bd4c16"><code>5b6b024</code></a>
Bump picomatch (<a
href="https://redirect.github.com/stylelint/stylelint/issues/9178">#9178</a>)</li>
<li><a
href="https://github.com/stylelint/stylelint/commit/7e25378e748a06e67bc0c8c467d3ed46a395d2ed"><code>7e25378</code></a>
Bump <code>@​csstools/css-syntax-patches-for-csstree</code> from 1.0.29
to 1.1.1 in the css...</li>
<li><a
href="https://github.com/stylelint/stylelint/commit/9edeff40a6cbcaff908294777e72e6ba9873c914"><code>9edeff4</code></a>
Group <code>csstree</code> and
<code>@csstools/css-syntax-patches-for-csstree</code> in dependabot
...</li>
<li><a
href="https://github.com/stylelint/stylelint/commit/2f7c0ca4da6ca860dec80ebd04fc02339d8fa7fe"><code>2f7c0ca</code></a>
Bump actions/download-artifact from 8.0.0 to 8.0.1 (<a
href="https://redirect.github.com/stylelint/stylelint/issues/9167">#9167</a>)</li>
<li><a
href="https://github.com/stylelint/stylelint/commit/59f310d6e4ca45f603f8d82dd250d49341c3a8f9"><code>59f310d</code></a>
Bump write-file-atomic from 7.0.0 to 7.0.1 (<a
href="https://redirect.github.com/stylelint/stylelint/issues/9169">#9169</a>)</li>
<li><a
href="https://github.com/stylelint/stylelint/commit/ab2ffcbae6691a3882bdbac058cebb108a7c57a0"><code>ab2ffcb</code></a>
Bump <code>@​vscode/windows-process-tree</code> from 0.6.3 to 0.7.0 (<a
href="https://redirect.github.com/stylelint/stylelint/issues/9170">#9170</a>)</li>
<li><a
href="https://github.com/stylelint/stylelint/commit/a9f3e5b3ffe9a18c361f643c6bd87036356f573e"><code>a9f3e5b</code></a>
Bump lint-staged from 16.3.3 to 16.4.0 (<a
href="https://redirect.github.com/stylelint/stylelint/issues/9171">#9171</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/stylelint/stylelint/compare/17.4.0...17.6.0">compare
view</a></li>
</ul>
</details>
<details>
<summary>Install script changes</summary>
<p>This version modifies <code>prepare</code> script that runs during
installation. Review the package contents before updating.</p>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=stylelint&package-manager=npm_and_yarn&previous-version=17.4.0&new-version=17.6.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>